# -*- coding: utf-8 -*-
"""Miniproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EvdC11IRv6iwliH1F1hAw_IfN9oRceqX
"""

sales = []
for i in range(0,7):
    value = int(input("Enter your sales:"))
sales.append(value)
print(sales)

sales = [800, 600, 400, 200, 300, 500, 100]
total_sales = sum(sales)
avg_sales = sum(sales)/len(sales)
highest_sales = max(sales)
lowest_sales = min(sales)
print(total_sales)
print(avg_sales)
print(highest_sales)
print(lowest_sales)

sales = [800, 600, 400, 200, 300, 500, 100]
avg_sales = sum(sales)/len(sales)
for sale in sales:
   if sale > avg_sales:
      print(sale)

sales = [800, 600, 400, 200, 300, 500, 100]
avg_sales = sum(sales)/len(sales)
count = 0
for days in sales:
   if days < avg_sales:
      count += 1
print(count)

sales = [800, 600, 400, 200, 300, 500, 100]
def calculate_total(sales):
    total = sum(sales)
    print("Total Sales:",total)
calculate_total(sales)

sales = [800, 600, 400, 200, 300, 500, 100]
def calculate_average(sales):
    average = sum(sales)/len(sales)
    print("Avg Sales:",average)
calculate_average(sales)

sales = [800, 600, 400, 200, 300, 500, 100]
def calculate_above_average(sales):
   average = sum(sales)/len(sales)
   for sale in sales:
      if sale > average:
       print("Sales:", sale)
calculate_above_average(sales)

sales = [800, 600, 400, 200, 300, 500, 100]
def calculate_below_average(sales):
   average = sum(sales)/len(sales)
   count = 0
   for day in sales:
      if day < average:
        count += 1
   print("Sales:",count)
calculate_below_average(sales)

sales = [800, 600, 400, 200, 300, 500, 100]
for sale in sales:
    print(sale)

sales = [800, 600, 400, 200, 300, 500, 100]
total = 0
for sale in sales:
    total += sale
print(total)

sales = [800, 600, 400, 200, 300, 500, 100]
for sale in sales:
    if sale > 300:
       print(sale)

sales = [800, 600, 400, 200, 300, 500, 100]
count = 0
for day in sales:
   if day < 300:
    count += 1
print("No.of days sales below 300:",count)

sales = [800, 600, 400, 200, 300, 500, 100]
list_com = [x**2 for x in sales]
print(list_com)

sales = [800, 600, 400, 200, 300, 500, 100]
new_sales = sales.append(450)
remove_sales = sales.remove(min(sales))
print("New list:", sales)

store_sales = [
    [250, 300, 150, 400, 500, 100, 350],  # Store 1
    [200, 400, 300, 500, 600, 150, 250]   # Store 2
]
for sale in store_sales: